easy_admin:
    design:
        menu:
            - {label: "Entities"}
            - label: "Posts"
              children:
                   - {entity: Post, label: "Posts list", icon: "th-list"}
                   - {entity: Post, label: "Add post", icon: "plus", params: {action: 'new'}}
            - label: "Category"
              children:
                  - {entity: Category, label: "List all categories", icon: "th-list"}
                  - {entity: Category, label: "Add category", icon: "plus", params: {action: 'new'}}
            - Tag
            - {label: "Settings"}
            #- User
            - {entity: User, icon: "user"}
    site_name: 'OverSeas <b>Media</b>'
    user:
        # display_name: false ( supprimer le nom user.unnamed )
        # display_avatar: false ( supprimer l'avatar )
        display_name: true
        display_avatar: true
        name_property_path : 'fullName' # property from User database
    entities:
        # List the entity class name you want to manage
        #- App\Entity\Post
        #- App\Entity\Category
        #- App\Entity\Tag
        #- App\Entity\User
        Post:
            class: App\Entity\Post
            label: "Post"
            form: # for working with the form
              fields:
                 - {type: 'group', icon: 'pencil', label: 'Basic Information', css_class: 'col-lg-7'}
                 - title
                 - {property: 'content', type: 'text_editor'}
                 - createdAt
                 - published
                 - {type: 'group', icon: 'th-list', label: 'Other Information', css_class: 'col-lg-5'}
                 - category
                 - tags
            list: # list all records
              collapse_actions: true
              actions: ['show', 'edit', 'delete']
              batch_actions: ['delete'] # delete and deselect (ajoute un checkbox)
              title: "Here you can change title Post by everything you want"
              filters: ['published']
            edit: # edit Post
              help: "Hello there"
              fields:
                 - '-tags' # disabled tags in edit data
            show: # show content Post
              fields:
                - title
                - {property: 'content', type: 'raw'}
                - createdAt
                - published
                #- content
        Category:
              class: App\Entity\Category
        Tag:
              class: App\Entity\Tag
              form:
                fields:
                  - name # show only the name, slug
                  - slug
        User:
              class: App\Entity\User
